### ISSUE TITLE
[Sound] Welcome message is playing twice

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#705] opened 2018-02-05 09:40 UTC

**Comment by CatmanIta** [comment] 2018-02-06 09:46
I cannot reproduce this. I tested with two new profiles. The Map_intro is played when accessing the map the first time after exiting the AnturaSpace after the Customization tutorial. 

The second time the map is accessed is after the first play session and the Shop tutorial. Then, the Assessment_Start_N is played (with N being either 1,2 or 3)

**Comment by FrancyCavallari** [comment] 2018-02-06 11:27
@zixofranic I tested also myself and I confirm that everything seems ok... can you please provide us more details about the problem in order to understand and reproduce it?

**Comment by zixofranic** [comment] 2018-02-06 11:38
It happened the first time the 2-1 was played ... I tried it by going back and playing the games and it didn't happen

**Comment by FrancyCavallari** [comment] 2018-02-06 11:41
Do you mean LB 2.1? In Stage 2?
We have a specifica "welcome" message for each of the 6 worlds... so it should not be the same dialog

**Comment by CatmanIta** [comment] 2018-02-06 17:10
Fixed in [e843343]

**Closed** 2018-02-06 17:25 UTC
Labels: DONE_2validate, audio, bug, low priority, needs feedback
