### ISSUE TITLE
[Map] The animation of unlock next PS is too slow

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#636] opened 2018-01-18 09:19 UTC
The animation of the little Dots and the next PS marker (pin or pencil) appearing is too slow and it could be nicer (now it's "robotic/cold").

**Comment by CatmanIta** [comment] 2018-01-18 17:27
Avoid clicking during this part.

**Comment by CatmanIta** [comment] 2018-01-18 19:06
Added better animation timings (as intended! they were too fast)

**Comment by FrancyCavallari** [comment] 2018-01-23 12:04
Can we speed up the appearence of the little Dots?
They are still too slow... we need this animation to be quick and eye-catching...

**Comment by CatmanIta** [comment] 2018-02-06 17:11
Fixed in [e843343]

**Closed** 2018-02-06 17:35 UTC
Labels: DONE_2validate, enhancement, low priority
